#<------ Archivo de Configuraciones ------>
#Thu Mar 26 09:47:09 MST 2026
Estilo=0
Fuente=Bernard MT Condensed
Idioma=ES
RutaTrabajo=C:\\Users\\diana\\OneDrive\\Documents\\GitHub\\Proyecto_Editor_Texto\\EditorDeTexto\\
Tamano=35