#<------ Archivo de Configuraciones ------>
<<<<<<< HEAD
#Thu Mar 26 09:47:09 MST 2026
Estilo=0
Fuente=Bernard MT Condensed
Idioma=EN
=======
#Wed Mar 25 20:55:12 MST 2026
Estilo=0
Fuente=Bernard MT Condensed
Idioma=ES
>>>>>>> parent of 0a0457a (comentario)
RutaTrabajo=C\:\\Users\\diana\\OneDrive\\Documents\\GitHub\\Proyecto_Editor_Texto\\EditorDeTexto\\
Tamano=35
