#<------ Archivo de Configuraciones ------>
#Wed Mar 25 20:40:29 MST 2026
Estilo=0
Fuente=Bernard MT Condensed
Idioma=EN
RutaTrabajo=C\:\\Users\\diana\\OneDrive\\Documents\\GitHub\\Proyecto_Editor_Texto\\EditorDeTexto\\
Tamano=35
